INSERT INTO orders VALUES (1, 'Skånekakor AB', CURRENT_DATE);
INSERT INTO orders VALUES (2, 'Skånekakor AB', CURRENT_DATE);
INSERT INTO orders VALUES (3, 'Finkakor AB', CURRENT_DATE);
INSERT INTO orders VALUES (4, 'Bjudkakor AB', CURRENT_DATE);
